name: Create rakudo-star

on:
    push:
    pull_request:

jobs:
    setup:
        runs-on: windows-2019
        steps:
            - name: Setup choco
              run: |
                bin/install_choco.cmd
