name: Create rakudo-star

on:
    push:
    pull_request:

jobs:
    choco:
        runs-on: windows-2019
        steps:
            - uses: actions/checkout@v2
            - name: API key
              run: choco apikey -k ${{ secrets.API_KEY }} -s https://push.chocolatey.org/
            - name: Cook templates
              run: gmake all
            - name: Test
              run: gmake test
