name: Create rakudo-star

on:
    push:
    pull_request:

jobs:
    setup:
        runs-on: windows-2019
        steps:
            - uses: actions/checkout@v2
            - name: Cook templates
              run: gmake all
            - name: Test
              run: gmake test
