name: Create rakudo-star

on:
    push:
    pull_request:

jobs:
    setup:
        runs-on: windows-2019
        steps:
            - uses: actions/checkout@v2
            - name: Setup choco
              shell: cmd
              run: |
                .\bin\install_choco.cmd
